/**
 * *************************************************************
 * file: GameOverGUI.java 
 * author: Diaz Disciples (Group name)
 * class: Computer Programming
 * Graphical User Interfaces - CS245
 * purpose: Game over screen
 * **************************************************************
 *
 */
package cs245quarterproject.src;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/*
 * @author David
 */
public class GameOverGUI extends javax.swing.JPanel {
    public GameOverGUI() {
        initComponents();
    }

    public GameOverGUI(String score) {
        initComponents();
        number.setText(score);
    }
    
    public void addScore(String score, String name){
        
        //Variable Declarations
        String[] names = new String[6];
        String[] scores = new String[6];
        int x = 0;
        Scanner input;
        
        //Open "data.text" and parse through lines
        //Ignore "....." value
        try {
            input = new Scanner(new File("data.text"));
            while(input.hasNext()){
                String a = input.next();
                String b = input.next();
                String c = input.next();

                names[x] = a;
                scores[x] = c;

                x++;
        }
        input.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        
        
        //Compare scores
        int z = 10;
        
        for(int i = 0; i < 5; i++)
        {
            if(Integer.parseInt(score) >= Integer.parseInt(scores[i]))
            {
                //Push lower "scores" down array
                for(int j = 0; j < 5 - i; j++)
                {
                    names[5 - j] = names[4 -j];
                    scores[5 - j] = scores[4 - j];  
                }
                
                //Set new "name" and "score"
                names[i] = name;
                scores[i] = score;
                
                break;
            }
        }
        
      
        //Output results into "data.text"
        String filename = "data.text";
        try {
            PrintWriter outputStream = new PrintWriter(filename);
            
            for(int i = 0; i < 5; i++)
            {
                String s = names[i] + " ..... " + scores[i];
                outputStream.println(s);
            }
            outputStream.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameOver = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        number = new javax.swing.JLabel();
        input = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gameOver.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        gameOver.setForeground(new java.awt.Color(204, 0, 0));
        gameOver.setText("GAME OVER");
        add(gameOver, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        score.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        score.setForeground(new java.awt.Color(0, 153, 0));
        score.setText("SCORE: ");
        add(score, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        number.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 70, 30));

        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });
        add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 130, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Insert Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        //"addScore" function
        addScore(number.getText(), input.getText());
        
        //Go back to main menu
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.getContentPane().removeAll();
        frame.repaint();
        
        Menu m = new Menu();
        frame.add(m);
        frame.setVisible(true);
    }//GEN-LAST:event_inputActionPerformed
                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameOverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameOverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameOverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameOverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameOverGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gameOver;
    private javax.swing.JTextField input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel number;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
