/**
 * *************************************************************
 * file: Menu.java 
 * author: Diaz Disciples (Group name)
 * class: Computer Programming
 * Graphical User Interfaces - CS245
 * purpose: Main menu screen
 * **************************************************************
 *
 */
package cs245quarterproject.src;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/*
 */
public class Menu extends javax.swing.JPanel {
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        play = new javax.swing.JButton();
        highscores = new javax.swing.JButton();
        credits = new javax.swing.JButton();
        labelPictureHangman = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        play.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        play.setText("Play");
        play.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        play.setPreferredSize(new java.awt.Dimension(85, 25));
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        add(play, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 110, 40));

        highscores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        highscores.setText("Highscores");
        highscores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        highscores.setPreferredSize(new java.awt.Dimension(85, 25));
        highscores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highscoresActionPerformed(evt);
            }
        });
        add(highscores, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 110, 40));

        credits.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        credits.setText("Credits");
        credits.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        credits.setPreferredSize(new java.awt.Dimension(85, 25));
        credits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsActionPerformed(evt);
            }
        });
        add(credits, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 110, 40));

        labelPictureHangman.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelPictureHangman.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPictureHangman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        add(labelPictureHangman, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 300, 310));
    }// </editor-fold>//GEN-END:initComponents

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        //Remove current JPanel and add new one
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.getContentPane().removeAll();
        frame.repaint();
        
        Hangman man = new Hangman();
        frame.add(man);
        frame.setVisible(true);
    }//GEN-LAST:event_playActionPerformed

    private void highscoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highscoresActionPerformed
        //Remove current JPanel and add new one
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.getContentPane().removeAll();
        frame.repaint();
        
        HighScores scores = new HighScores();
        frame.add(scores);
        frame.setVisible(true);
    }//GEN-LAST:event_highscoresActionPerformed

    private void creditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsActionPerformed
        //Remove current JPanel and add new one
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.getContentPane().removeAll();
        frame.repaint();
        
        Credits credit = new Credits();
        frame.add(credit);
        frame.setVisible(true);
    }//GEN-LAST:event_creditsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton credits;
    private javax.swing.JButton highscores;
    private javax.swing.JLabel labelPictureHangman;
    private javax.swing.JButton play;
    // End of variables declaration//GEN-END:variables
}
